### ISSUE TITLE
[Discussion] Sub-file batching — Decouple GPU memory usage from model file size

### ISSUE THREAD

**Issue by ABNER-1** [foundation-model-stack/fastsafetensors#71]
### Current state: Loading granularity is tightly coupled with model file size

Currently, fastsafetensors requires each rank to load an **entire** safetensors shard file into GPU memory (device buffer) at once, then broadcast the tensors within it to all other ranks before moving on to the next batch.

This means the **peak extra GPU memory per rank** is at least the size of a single safetensors shard file (for the device buffer), plus additional overhead from clone/empty tensors allocated during broadcast.

For models with small shards (e.g., 2–5 GB per file), this overhead is manageable. However, state-of-the-art open-source models are shipping increasingly large individual shard files:

| Model              | Shard size    | Params |
|--------------------|---------------|--------|
| DeepSeek-V3        | ~4 GB         | 671B   |
| Qwen3.5-397B-A17B  | ~8.6 GB       | 397B   |
| DeepSeek-V4 (base) | **~25 GB**    | 861B   |
| DeepSeek-V4 (fp4)  | **~13.9 GB**  | 861B   |

A 25 GB shard means **25 GB of extra GPU memory just for the file buffer** — on top of the memory needed for the model weights themselves. On an 80 GB GPU, this alone consumes 31% of total VRAM, making OOM very likely.

This effectively **narrows fastsafetensors' applicability**, even though achieving optimal storage performance does not necessarily require loading an entire file at once.

### Root cause: The Loader's core interface semantics operate at file granularity

The root cause of this limitation is not in any particular upper-layer caller (such as `PipelineParallel`), but in the fact that **the two core interfaces of `BaseSafeTensorsFileLoader` themselves have "entire file" as their semantic granularity**:

```python
# fastsafetensors/loader.py

def add_filenames(self, filenames: Dict[int, List[str]]):
    """Register files to ranks to be copied at copy_file_to_device()."""
    # Registers by filename, fully parsing metadata for each file and associating it with a rank
    for rank in filenames.keys():
        realpath = filenames[rank][next_idx]
        metadata = SafeTensorsMetadata.from_file(realpath, self.framework)
        self.meta[realpath] = (metadata, rank)
        ...

def copy_files_to_device(self, ...) -> FilesBufferOnDevice:
    """trigger copying all the files to device buffers."""
    # Iterates over each registered file, creates a copier and allocates a device buffer for the entire file
    for _, (meta, rank) in sorted(self.meta.items(), ...):
        copier = self.copier_constructor(meta, self.device, self.framework)
        factory = LazyTensorFactory(meta, ...)
        factory.submit_io(use_buf_register, max_copy_block_size)
        ...
```

- **`add_filenames`**: Input is `Dict[int, List[str]]` (rank → file path list), with granularity at the whole-file level.
- **`copy_files_to_device`**: Iterates over all registered files, creates a `CopierInterface` instance **for each entire file**, and submits I/O. Internally, `CopierInterface.submit_io` allocates a device buffer equal to the entire file size (e.g., `alloc_tensor_memory(total_length, ...)` in `NoGdsFileCopier`).

Since the Loader's interface semantics are at the file level, **all upper-layer callers that depend on this interface** — whether `PipelineParallel`, `UnifiedLoader`, or user code directly using `SafeTensorsFileLoader` — can only perform batch partitioning at the "file" granularity, **unable to split tensors from a single file across multiple batches**.

As an example, `PipelineParallel`'s batching logic is constrained by this to group exactly `world_size` files per batch:

```python
# fastsafetensors/parallel_loader.py
def _create_batches(self, pg) -> List[List[str]]:
    batch_size = pg.size()  # == world_size
    return [
        self.hf_weights_files[i : i + batch_size]
        for i in range(0, len(self.hf_weights_files), batch_size)
    ]
```

To enable sub-file batching, the core requirement is to extend or redesign the Loader's interface semantics to support tensor-level (or byte-range-level) registration and loading.

## Related

- The existing `max_copy_block_size` (default 16 GB) controls the maximum *single I/O submission* size, but does **not** limit the total device buffer allocation per file — the entire file's buffer is allocated upfront regardless of this setting.
- `queue_size` controls the number of *concurrent batches* in the pipeline, but each batch still loads a full file per rank.

## Discussion

The above is an idea based on GPU memory pressure we observed while deploying large model inference in production. We're sharing it to open a discussion and gauge whether this direction has broad value for the community.

This is not a proposal that needs to land in the short term, nor does it have to be completed in a single PR. If the direction is considered valuable, it could be approached incrementally, for example:

1. **Phase 1**: Loader interface extension — enable `BaseSafeTensorsFileLoader` to support tensor-level (or byte-range-level) registration and loading. This is the foundation.
2. **Phase 2**: Fixed byte budget sub-batching — implement `max_batch_bytes` in `PipelineParallel`, partitioning tensors into sub-batches based on pre-read header metadata.
3. **Phase 3** (optional): Adaptive batching and batch read-order optimization.

### Questions for discussion

- Have you encountered similar GPU memory bottlenecks? How large are your typical shard files?
- For extending the `add_filenames` / `copy_files_to_device` interface semantics, are there better approaches?
- Are there complexity issues or edge cases that might have been overlooked?

Feedback welcome 🙏

**Comment by ABNER-1** [comment]
## One possible approach

Below is one possible implementation approach I've been thinking about. It's not the only way to solve this — just a concrete sketch to help ground the discussion.

The core idea: introduce **sub-file batching** — allow each batch to load only a portion of a file (a "chunk"), rather than requiring the entire file to be loaded at once. The key insight is:

> The minimum loadable unit is **the largest single tensor** within the file — not the entire file.

### Mechanism

Add a new configuration parameter (e.g., `max_batch_bytes`) to control the maximum bytes loaded per rank per batch. The loader's workflow would become:

1. **Pre-read tensor metadata** (safetensors headers) for all files to determine individual tensor sizes and offsets.
2. **Partition tensors into sub-batches** such that each sub-batch's total size does not exceed `max_batch_bytes`. Constraints:
   - `max_batch_bytes >= max(tensor_size for all tensors across all files)` — i.e., at least the largest single tensor must fit.
   - Tensors from the same file can be split across different sub-batches.
3. Execute **load → broadcast → release** per sub-batch, then load the next, keeping peak buffer memory bounded by `max_batch_bytes` (per rank).

### Suggested API

```python
# Option A: LoaderConfig parameter
config = LoaderConfig(
    max_batch_bytes=4 * 1024**3,  # 4 GB max buffer per rank per batch
    # ...
)

# Option B: Environment variable
# FASTSAFETENSORS_MAX_BATCH_BYTES=4294967296
```

When `max_batch_bytes` is not set (default), current behavior is preserved — each batch loads one complete file per rank (backward compatible).

### Batching strategy options

Two possible strategies:

1. **Fixed byte budget** (`max_batch_bytes`): Pack as many tensors as fit within the byte budget, regardless of file boundaries. Simple and predictable.
2. **Adaptive batching**: Automatically choose sub-batch size based on available GPU memory at load time. Can also reorder the read sequence within batches using rules/algorithms to balance data volume across workers for optimal loading performance. Most complex but most user-friendly.

We suggest starting with **option 1 (fixed byte budget)** as it is the simplest to implement and reason about.

### Implementation notes

The main changes would involve:

- **`fastsafetensors/config.py`**: Add `max_batch_bytes: Optional[int] = None` to `LoaderConfig`.
- **`fastsafetensors/parallel_loader.py`**:
  - Modify `_create_batches` to produce sub-file-level batches when `max_batch_bytes` is set.
  - Each "batch item" would carry not just a filename but also the tensor key list (or byte offset ranges) to load for that batch, with contiguous reads within each batch.
- **`fastsafetensors/loader.py`** (or the copier layer):
  - Support partial file reads — loading only specified byte ranges from a safetensors file rather than the entire data section.
  - This is feasible because safetensors uses a flat layout with tensor offsets encoded in the header.
- **`fastsafetensors/tensor_factory.py`**:
  - `LazyTensorFactory` would need to handle partial tensor sets per file (not all tensors from a file are available in a single batch).

### Complexity considerations

- **Header parsing**: The safetensors header contains all tensor metadata (name, dtype, shape, offsets). It is typically small (< 1 MB) and can be read once upfront with negligible cost.
- **Partial reads**: Both `pread`-based (NoGDS) and GDS-based copiers support offset-based reads, so sub-file I/O should be straightforward.
- **Broadcast ordering**: All ranks must agree on which tensors are in each sub-batch and in what order. This can be achieved by having all ranks deterministically compute the batching plan from the same metadata (for V1).
- **Backward compatibility**: When `max_batch_bytes` is not set, behavior is identical to today.

## Expected impact

- **Decouple** model shard file size from GPU memory overhead during loading.
- **Broaden applicability** to models with very large shard files (25 GB+).
- **Give users control** over the memory/throughput tradeoff during model loading.
- **No regression** — existing users' default behavior is unchanged.

**Comment by takeshi-yoshimura** [comment]
@ABNER-1 
I agree that we need to deal with very large shard files and chunking is a natural direction. Providing `max_batch_bytes` is absolutely useful, but, I am not sure if adaptive batching performs well (sounds like long-term research since the best size varies depending on hardware configuration and loader mode).

If you have bandwidth, can you please implement this? This kind of work requires careful performance analysis. So, maybe you can reuse `perf/` scripts for this work.

**Comment by gitbisector** [comment]
+1 on dropping below file granularity. I'd like this API to also cover a second use case (the I/O side, not just memory).

Using the unified copier from #60, loading DeepSeek-V4-Flash on 2× DGX Spark (GB10) under expert parallelism hits the same file-granularity limit, but there the cost is redundant I/O rather than peak memory: each EP rank reads every expert's bytes and discards the ones it doesn't own. On a 2-way EP split that's ~2× the necessary read per rank.

A prototype "EP-slice" path where each rank reads only the byte ranges of its owned experts cut V4-Flash weight load from ~17.6s to ~13s by reading roughly half the bytes per rank. The mechanism is the same sub-file/byte-range reading proposed here; the only addition is letting the caller pick which ranges, not just chunk size.

For this sub-file API then: if max_batch_bytes/chunking also exposes (now or later) a way to select a subset of tensors/byte-ranges per rank, that single primitive covers both motivations, memory decoupling (this issue) and skipping unowned experts under EP. My prototype and GB10 benchmarks are available if useful.

**Comment by takeshi-yoshimura** [comment]
@gitbisector 
Thanks, that would be very useful. If you already have a prototype, could you please open a PR with them? The GB10 benchmark numbers would also be very helpful for understanding the impact.

I expect this may overlap or conflict with the chunking work, so I may not merge it immediately. However, having the prototype as a PR would make it faster to push things forward.

**Comment by takeshi-yoshimura** [comment]
@ABNER-1 
Hello, are you still working on this now? I would like to proceed the PR #81.

**Comment by gitbisector** [comment]
@takeshi-yoshimura 
I've been running #81 for a while and have implemented Phase 2 on top of it: max_batch_bytes partitions each file's tensors into sub-batches by byte budget (headers pre-read, largest-tensor floor enforced), and the copiers allocate only each chunk's span — so peak device memory is bounded by the budget rather than the shard size. Measured on a 46-shard/160 GB checkpoint: a fixed 2 GiB budget caps the transient buffer at ~2 GiB for ~6% wall-time; 1 GiB caps it at ~1 GiB for ~50%.

Since a fixed budget pays chunking cost on every shard even while device memory is still empty, there's a second, smaller piece: per-file budgets precomputed from the safetensors headers plus one free-memory query — whole-file loads while headroom is ample, chunking only the tail shards, and a plan-time "model does not fit" error instead of an OOM mid-load. Deterministic (same files + budget → same plan), so it stays out of the runtime-tuning territory discussed above. That variant matched full-speed loading at every feasible budget in my tests.

I'd like to send both as draft PRs (sub-batching first, the budget planner as a follow-up) once #81 settles — easier to discuss the API shape against real code.

**Comment by gitbisector** [comment]
Both draft PRs are up as promised: #90 (max_batch_bytes sub-file chunk loading) and #91 (the deterministic fit planner, stacked on it). #91 also accounts for a unified-memory subtlety measured on GB10 along the way: the mmap+pin fallback's chunks cost ~2× their span there, while the O_DIRECT path stays ~1×.

**Comment by takeshi-yoshimura** [comment]
@gitbisector 
Thanks for the PRs again. We already have multiple changes on the current version and seems the two PRs affect the broad critical path for loader/copier. Let me move the version to 0.3.3 and hopefully merge the two PRs in 0.4.

**Comment by takeshi-yoshimura** [comment]
@gitbisector 
I will soon release 0.4 with this change. Do you have bandwidth to push your change to the vllm upstream? I'll do it if you cannot.

**Comment by gitbisector** [comment]
@takeshi-yoshimura yes I could do it — I wrote the current fastsafetensors_weights_iterator there (vllm#40183), so it's the same function either way.

One scope question before I start: by "your change," do you mean specifically wiring up max_batch_bytes / device_memory_budget from #90/#91, or the broader loader integration? I ask because I've been running a vLLM patch that uses more of the merged surface than just those two, and I'd rather send what's actually useful to you than guess.

One thing worth having regardless of who writes it: vLLM needs accumulate_resident=False. vLLM copies each yielded tensor into a preallocated model parameter and drops it, so the consumer never accumulates. With the default True the planner raises BudgetInfeasibleError on any model that doesn't trivially fit because it counts the whole checkpoint. Took me a while to track down.

Separately, all_local=True (from #81, so already in 0.3.3) turned out to be a much bigger win in vLLM than I expected. DeepSeek-V4-Flash, 155.4 GiB, TP=2 on 2× RTX PRO 6000: default loader ~800s, fastsafetensors with broadcast 336s, and all_local 41s. The mechanism is reader concurrency rather than any bandwidth ratio — broadcast funnels all I/O through rank 0 at queue depth 1 while NVMe throughput scales with concurrent readers. It costs N× the bytes read, so PR would have it opt-in.

So my plan is a single vLLM PR once 0.4 is on PyPI, carrying both all_local and the planner wiring, rather than sending all_local separately against a >= 0.3.3 floor. Bundling avoids raising vLLM's fastsafetensors floor twice in two months, and I can validate both arms before then — my test image already tracks main, so it has the full 0.4 surface today.

**Comment by gitbisector** [comment]
Follow-up now that I've written the vLLM side: the branch is done and only waits on 0.4:
https://github.com/gitbisector/vllm/tree/feat/fastsafetensors-all-local-fit-planner

pip-compile can't resolve `fastsafetensors>=0.4` until it's published, which is the sole remaining CI failure — everything else passes.

Two things before you tag.

Export `BudgetInfeasibleError`. It only lives in `_planner` today. vLLM treats an infeasible plan as non-fatal — it logs and falls back to unplanned whole-shard loading rather than refuse a model that might still fit — so it needs to catch that exception specifically rather than any `ValueError` the constructor might raise. Right now that means either importing a private module or catching bare `ValueError` in upstream vLLM. It already subclasses `ValueError`, so exporting it doesn't break anyone.

`accumulate_resident` can't describe a consumer that offloads part of what it is given. I hit this on another integration (sglang) that relocates a subset of yielded tensors to host memory during the load. `True` over-counts resident by the offloaded bytes and refuses plans that would fit; `False` under-counts the bytes that genuinely stay. Neither is right, so the fit planner isn't usable there and I fell back to `max_batch_bytes`.

If 0.4 wants to cover offloading consumers, a per-tensor residency predicate would model it where a binary can't. `FileWeightStats.kept_bytes` currently means both "bytes read" and "bytes that stay resident", which is only the same number when the consumer keeps everything. Splitting it looks small:

- `FileWeightStats` gains `resident_bytes`, filled by a `resident_tensor` predicate in `collect_file_stats(metas, keep_tensor=None, resident_tensor=None)`
- `_group_resident` sums `resident_bytes` instead of `kept_bytes`
- the `resident = group_resident[i] if accumulate_resident else 0` ternaries in both `plan_file_budgets` and `fit_queue_size` collapse to `resident = group_resident[i]`, since residency now lives in the stats
- `accumulate_resident` stays at constructor level as shorthand — `True` sets `resident_tensor = keep_tensor`, `False` sets `lambda _: False` — and stops being passed to the planner, so it can't zero out the residency the stats just computed

It reuses the `keep_tensor` predicate shape the planner already uses rather than adding a new concept, and no caller has to change.

One thing I don't have a clean answer for: `account_for_yield_clone = self.need_clone and not self.accumulate_resident`. Under a mixed consumer the reservation wants "any non-resident yield" rather than "no yields are resident". That happens to be true in my case, but only by accident, so it probably needs deciding rather than deriving.

**Comment by takeshi-yoshimura** [comment]
@gitbisector 
Thanks for putting this together. The broader integration sounds good to me, and a single vLLM PR covering both the planner and opt-in all_local makes sense.

One addition I’d like to see is use_chunk_budget_as_allocation_size. It helps reduce allocator fragmentation and improve performance when the model barely fits in GPU memory.

The all_local result is encouraging. The branch currently does not have vLLM’s EP weight filter, so combining that with all_local could be a useful follow-up for DeepSeek and other MoE models.

> One small ask before you tag: could you export BudgetInfeasibleError from fastsafetensors/__init__.py? It only lives in _planner today. vLLM treats an infeasible plan as non-fatal — it logs and falls back to unplanned whole-shard loading rather than refuse a model that might still fit — so it needs to catch that exception specifically rather than any ValueError the constructor might raise. Right now that means either importing a private module or catching bare ValueError in upstream vLLM, and I'd rather do neither. It already subclasses ValueError, so exporting it doesn't break anyone.

Yes, exposing BudgetInfeasibleError makes sense independently of the fallback policy. I will check your PR #108 soon.

I’m less convinced about automatically retrying without a budget. Retrying with whole-shard loading could then make memory pressure worse. My preference would be to stop with an actionable error by default and let users explicitly override or disable the budget. There are cases where the reserved headroom could allow the fallback to succeed, though, so I think the vLLM PR is a good place to agree on that policy.

**Comment by gitbisector** [comment]
Thanks, I agree on all 3.

`use_chunk_budget_as_allocation_size` is now in, enabled whenever the loader plans against a budget. The branch has been force-pushed since the link above, so it has moved.

On the fallback: I've split it by where the budget came from, which I think gets your semantics without the regression I was worried about.

- vLLM derived it (the default): free memory minus a reserve, all-reduced MIN across ranks. That is an estimate, and the planner is deliberately conservative on top of it, so an infeasible plan warns and stages whole shards. Failing here would turn a load that works today into an error on a number vLLM guessed.
- The user set `VLLM_FASTSAFETENSORS_DEVICE_MEMORY_BUDGET`: enforced. An infeasible plan stops with the planner's error, which names the shortfall. `0` disables planning entirely.

So "stop with an actionable error" is the behaviour whenever someone states a budget, and only the guess stays advisory. If you would rather the default were strict as well I can flip it — it is one condition — but I would want that to be deliberate, since it changes loads that work today.

Agreed on EP. vLLM computes `local_expert_ids` and passes it to the plain safetensors iterator but not to the fastsafetensors one, so the filter is absent on this path rather than conflicting with it. Wiring that to `tensor_filter` alongside `all_local` is the natural next step: each rank then reads only the experts it owns instead of every rank reading everything, which is exactly where `all_local`'s read amplification costs the most. Could potentially put that in this vLLM PR rather than a follow-up — does `ep_slice`'s expert naming line up with what vLLM expresses as `local_expert_ids`, or is there a translation layer in between? If it is a clean fit I would rather land it together.

And thanks for looking at #108.

**Comment by takeshi-yoshimura** [comment]
My concern comes from the original motivation in this issue: whole-shard staging ties temporary GPU memory usage to shard size and can cause OOM. Falling back to that same path when the planner cannot fit seems to reintroduce the original problem precisely under memory pressure.

I understand preserving previously successful loads, but I’d prefer keeping whole-shard fallback explicit rather than automatic. A conservative estimate can reject a load that would fit, but it doesn’t establish that whole-shard staging will fit.

**Comment by takeshi-yoshimura** [comment]
This is especially concerning on unified-memory systems, where severe memory pressure can affect the entire host and potentially leave it unresponsive, rather than simply failing the model load.

**Comment by gitbisector** [comment]
You're right. I was treating the fallback as "load without a bound", but it is "load with the worst bound": whole-shard staging needs a buffer at least as large as the tensor that would not fit. So when the planner refuses, whole-shard staging is strictly more likely to OOM, not less.

Proposing instead then: an infeasible plan raises, and vLLM catches `BudgetInfeasibleError` only to re-raise it with the planner's shortfall plus the remedy — `VLLM_FASTSAFETENSORS_DEVICE_MEMORY_BUDGET=0` disables planning and stages whole shards. Whole-shard stays reachable, but only because someone asked for it, which I take to be your "explicit rather than automatic" — one behaviour instead of two.

Does that match what you had in mind? If so I will update the branch.

And thanks for merging #108.

**Comment by takeshi-yoshimura** [comment]
Yes, that matches what I had in mind. Thanks for revisiting it. An infeasible plan should stop with an actionable error, while whole-shard loading remains an explicit opt-in.  One small wording point: please describe VLLM_FASTSAFETENSORS_DEVICE_MEMORY_BUDGET=0 as an override that removes the memory bound and may cause OOM, rather than a remedy for insufficient memory. Otherwise, this sounds good to me.

I will release 0.4 with #107 after I confirm all my GPU tests cleanly finish. thanks.

**Comment by takeshi-yoshimura** [comment]
0.4 is out. the remaining task to close this issue is to update vllm in my understanding.

**Comment by gitbisector** [comment]
No vLLM PR yet — 0.4.0 already delivers the speed win with no code change for me:
default loader 761.84 s vs `--load-format fastsafetensors` on stock vLLM main
26.52 s (n=3 each, non-overlapping). And no configuration here has needed a budget set — the KV pool
is allocated after the weights and comes out larger than any single shard
(10.8 vs 3.4 GiB on this box), so anything with usable context already has room
to stage a whole file. Only four public checkpoints that I could find ship shards over
15 GB.

Did build an artificial case to check the planner itself works —
`deepseek-ai/DeepSeek-V4-Flash-DSpark` re-sharded to 7 x 25 GiB, bitwise
identical — and it fails exactly as this issue describes: at 20.20 GiB free,
stock asks for the whole 25.00 GiB and OOMs, while passing `device_memory_budget`
derives 19.19 GiB, plans inside the shard, and loads.

@ABNER-1 — is there a deployment actually hitting this? A real checkpoint and GPU
configuration would really help the case for putting up a PR. The wiring is up meanwhile:
https://github.com/vllm-project/vllm/compare/main...gitbisector:vllm:feat/fastsafetensors-all-local-fit-planner

**Comment by takeshi-yoshimura** [comment]
@gitbisector 
I saw OOM with [meta-models/Muse-Glimmer-30B](https://huggingface.co/meta-models/Muse-Glimmer-30B/tree/main) on a single A100/H100 80GB VRAM.

**Comment by gitbisector** [comment]
@takeshi-yoshimura, thank you for the pointer to [meta-models/Muse-Glimmer-30B](https://huggingface.co/meta-models/Muse-Glimmer-30B/tree/main). Was able to reproduce on RTX 6000 PRO (96GB) and the PR is now up.
